FROM python:3.12-slim

WORKDIR /app

# Copy the project files
COPY integration-tests integration-tests/
COPY backend-utils backend-utils/
COPY common-utils common-utils/
COPY api api/

# Install dependencies
RUN pip install --no-cache-dir \
                -e ./api \
                -e ./backend-utils \
                -e ./common-utils \
                pytest>=8.4.1 \
                pytest-asyncio>=1.1.0

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

# TODO: support uv to be able running other tests
CMD ["sh", "-c", "pytest integration-tests/test_bash_executor.py -v --run-docker; exit 0"]
