repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-added-large-files
      args: ['--maxkb=2048']
    - id: check-shebang-scripts-are-executable
    - id: check-json
    - id: check-toml
    - id: check-xml
    - id: check-yaml
      args: [ "--allow-multiple-documents" ]
      exclude: ^charts/.+/templates/
    - id: end-of-file-fixer
    - id: name-tests-test
      args: [ "--pytest-test-first" ]
      files: ^.*-tests/.*\.py$
      exclude: ^.*-tests/(utils|config|test_projects)/
    - id: trailing-whitespace
      args: [ "--markdown-linebreak-ext=md" ]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.8
  hooks:
    - id: ruff-check
      args: [ "--fix", "--exit-non-zero-on-fix" ]
      files: \.py$
    - id: ruff-format
      files: \.py$
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.10.9
  hooks:
    - id: uv-lock
      files: \.toml$
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.30
  hooks:
    - id: helmlint
