[supervisord]
nodaemon=true
silent=true
pidfile=/tmp/supervisord.pid
logfile=/tmp/supervisord.log
logfile_maxbytes=0
loglevel=info

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[unix_http_server]
file=/tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:orchestrator]
process_name=orchestrator
numprocs=1
priority=2
command=python -m idegym.orchestrator.main
stopasgroup=true
killasgroup=true
autorestart=false
startsecs=0
startretries=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
redirect_stderr=false

[eventlistener:orchestrator-exit]
command=/usr/local/bin/kill-supervisor --watch=orchestrator --pidfile=/tmp/supervisord.pid
events=PROCESS_STATE_EXITED,PROCESS_STATE_FATAL
autorestart=false
startsecs=0
startretries=0
