apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "idegym.fullname" . }}
  labels:
    {{- include "idegym.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "idegym.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "idegym.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "{{ .Values.service.containerPort }}"
    spec:
      serviceAccountName: {{ include "idegym.deployment.serviceAccountName" . }}
      {{- with .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: orchestrator
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          env:
            - name: __POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.uid"
            - name: __POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.name"
            - name: __NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
            - name: __NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: "spec.nodeName"
            {{- with .Values.deployment.log }}
            - name: IDEGYM_LOG_LEVEL
              value: {{ quote .level | upper }}
            - name: IDEGYM_LOG_JSON_FORMAT
              value: {{ quote .json | title }}
            {{- end }}
            - name: IDEGYM_MANAGER_PORT
              value: {{ .Values.service.containerPort | quote }}
            - name: IDEGYM_OTEL_ATTRIBUTES
              value: |-
                { k8s.pod.uid: "$(__POD_UID)", k8s.pod.name: "$(__POD_NAME)", k8s.namespace.name: "$(__NAMESPACE)", k8s.node.name: "$(__NODE_NAME)" }
            - name: IDEGYM_OTEL_SERVICE_NAME
              value: {{ include "idegym.fullname" . | quote }}
            {{- with .Values.deployment.otel.tracing }}
            - name: IDEGYM_OTEL_TRACING_ENDPOINT
              value: {{ .endpoint | quote }}
            - name: IDEGYM_OTEL_TRACING_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "tracing"
                  key: "username"
                  optional: true
            - name: IDEGYM_OTEL_TRACING_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "tracing"
                  key: "password"
                  optional: true
            {{- end }}
            - name: IDEGYM_UVICORN_WORKERS
              value: {{ .Values.deployment.uvicornWorkers | quote }}
            {{- with .Values.deployment.sqlalchemy }}
            - name: IDEGYM_SQLALCHEMY_POOL_SIZE
              value: {{ .poolSize | quote }}
            - name: IDEGYM_SQLALCHEMY_MAX_OVERFLOW
              value: {{ .maxOverflow | quote }}
            {{- end }}
            - name: POSTGRES_DB
              {{- if .Values.deployment.database.name }}
              {{- include "idegym.envSource" .Values.deployment.database.name | nindent 14 }}
              {{- else if .Values.postgresql.enabled }}
              value: {{ include "idegym.subchart.postgresql.v1.database" . | quote }}
              {{- else }}
              {{- required "Database name must be specified!" .Values.deployment.database.name }}
              {{- end }}
            - name: POSTGRES_HOST
              {{- if .Values.deployment.database.host }}
              {{- include "idegym.envSource" .Values.deployment.database.host | nindent 14 }}
              {{- else if .Values.postgresql.enabled }}
              value: {{ include "idegym.subchart.postgresql.v1.primary.fullname" . | quote }}
              {{- else }}
              {{- required "Database host must be specified!" .Values.deployment.database.host }}
              {{- end }}
            - name: POSTGRES_PORT
              {{- if .Values.deployment.database.port }}
              {{- include "idegym.envSource" .Values.deployment.database.port | nindent 14 }}
              {{- else if .Values.postgresql.enabled }}
              value: {{ include "idegym.subchart.postgresql.v1.service.port" . | quote }}
              {{- else }}
              {{- required "Database port must be specified!" .Values.deployment.database.port }}
              {{- end }}
            - name: POSTGRES_USER
              {{- if .Values.deployment.database.username }}
              {{- include "idegym.envSource" .Values.deployment.database.username | nindent 14 }}
              {{- else if .Values.postgresql.enabled }}
              value: {{ include "idegym.subchart.postgresql.v1.username" . | quote }}
              {{- else }}
              {{- required "Database username must be specified!" .Values.deployment.database.username }}
              {{- end }}
            - name: POSTGRES_PASSWORD
              {{- if .Values.deployment.database.password }}
              {{- include "idegym.envSource" .Values.deployment.database.password | nindent 14 }}
              {{- else if .Values.postgresql.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "idegym.subchart.postgresql.v1.secretName" . | quote }}
                  key: {{ include "idegym.subchart.postgresql.v1.userPasswordKey" . | quote }}
              {{- else }}
              {{- required "Database password must be specified!" .Values.deployment.database.password }}
              {{- end }}
            {{- with .Values.deployment.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.deployment.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 60
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
