apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "idegym.fullname" . }}
  labels:
    {{- include "idegym.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  {{- with .Values.rbac.extraRules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
