from idegym.api.status import Status
from pydantic import BaseModel, Field


class FileRequest(BaseModel):
    file_path: str


class CreateFileRequest(FileRequest):
    content: str


class EditFileRequest(FileRequest):
    start_line: int = Field(ge=0)
    end_line: int = Field(ge=0)
    new_content: str


class PatchFileRequest(FileRequest):
    """Applies a unified diff patch generated by `diff_patch.compute_diff`."""

    patch: str


class FileResult(BaseModel):
    status: Status
