from idegym.api.status import Status
from pydantic import BaseModel, Field


class FileRequest(BaseModel):
    file_path: str = Field(description="File path")


class CreateFileRequest(FileRequest):
    content: str = Field(description="File content")


class EditFileRequest(FileRequest):
    start_line: int = Field(description="Start line of the replacement", ge=0)
    end_line: int = Field(description="End line of the replacement", ge=0)
    new_content: str = Field(description="New content")


class PatchFileRequest(FileRequest):
    """Applies a patch generated by `diff_patch.compute_diff`"""

    patch: str = Field(description="Patch to be applied")


class FileResult(BaseModel):
    status: Status = Field(description="Operation status")
