defaults: # https://hydra.cc/docs/tutorials/basic/your_first_app/composition/
  - _self_
  - logging: base
  - orchestrator: base
  - otel: base
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .
