apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: idegym

labels:
  - pairs:
      app.kubernetes.io/part-of: idegym
    includeSelectors: false

resources:
  # PostgreSQL
  - postgresql/service.yaml
  - postgresql/statefulset.yaml
  # Orchestrator
  - orchestrator/service-account.yaml
  - orchestrator/deployment.yaml
  - orchestrator/service.yaml
  - orchestrator/ingress.yaml
  # Prometheus
  - prometheus/service-account.yaml
  - prometheus/configmap.yaml
  - prometheus/deployment.yaml
  - prometheus/service.yaml
  # Grafana
  - grafana/configmap.yaml
  - grafana/deployment.yaml
  - grafana/service.yaml
  # Tempo
  - tempo/configmap.yaml
  - tempo/deployment.yaml
  - tempo/service.yaml
