apiVersion: v1
kind: Service
metadata:
  name: tempo
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/component: tracing
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tempo
  ports:
    - port: 3200
      targetPort: http
      protocol: TCP
      name: http
    - port: 4317
      targetPort: otlp-grpc
      protocol: TCP
      name: otlp-grpc
    - port: 4318
      targetPort: otlp-http
      protocol: TCP
      name: otlp-http
